language: objective-c
osx_image: xcode11

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8

addons:
  ssh_known_hosts: github.com

notifications:
  email: false

before_install:
  - env
  - locale
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
  - pod --version
  - pod setup --silent > /dev/null
  - pod repo update --silent
  - xcpretty --version
  - xcodebuild -version
  - xcodebuild -showsdks

script:
  - set -o pipefail

  - echo Check if the library described by the podspec can be built
  # Run full subspecs linting consuming too much of build time because CocoaPods use source code of Pods
  # Since`libx265` && `libde265` is Pod and have their own linting, don't waste time to lint full subspecs combination
  - pod lib lint --use-libraries --allow-warnings --no-subspecs --fail-fast

  - echo Build example
  - pod install --project-directory=Example
  - xcodebuild build -workspace Example/SDWebImageAVIFCoder.xcworkspace -scheme 'SDWebImageAVIFCoder-Example' -sdk iphonesimulator -destination 'name=iPhone 8' -configuration Debug | xcpretty -c
  - xcodebuild build -workspace Example/SDWebImageAVIFCoder.xcworkspace -scheme 'SDWebImageAVIFCoder-Example macOS' -sdk macosx -configuration Debug | xcpretty -c
